on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: D1
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        cd /inputs/stylegan2
        python run_generator.py
      image: tensorflow/tensorflow:1.14.0-gpu-py3
